name: Sukhpreet Singh
about: Yoga Instructor, Software Developer, Content Creator and Basketball Player
image:
  src: /images/profile.jpg
  alt: Avatar
links:
  email: mailto:sukhpreetben10@gmail.com
  github: https://github.com/q1b
  linkedin: https://linkedin.com/in/q1b
  x: https://twitter.com/_q1b_